---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgB71K6TIw/xo7V+oWFv7XxRLE4li44SDah0D/xt53ZmoGfJD0wKP251VV/JaP/0ONaCy3dXYBFBHBBMiTVZTG3YsaDhzJqPMOtCbM6e8TDYmYU+teiBk+Vz5dLHvqMicGdZKP4wQ8umzYsPOz2Wq1s1Imh+fdqrRWaIDAa2vsC14KidBEbaoWQSkAGh4yRM5EDZ8LVrMTi5tvkd7ChmW4LOrMQk7NmW2+DsdUyBtH7Cs9ZW8FyXVFdprcUssLedyf4dk7/kQqdqe9JCiWNYDxbFY9xOhTw8nkeHKSKwjCnzvNViL3CW3/EQmhvsFOHDFMxWndXEMz67kLgWGUE2RX9uM9mksS4WRDN6qmM7uQ3EqO9k0JTYcL11ON2RUF6OfjFPL1SPNi/0j5XjnZeWHZUSttoXnrFLUUwMfJDjm2PDXUWrmK2isVAtLI5IodfRCB1NXJo5KitZX5M4q54w2N6W0qNeBuIEqnLP/qXYYFJAXnmML5BzbQ/X3T5qsfCHY4+GmapMEKtQIAgNAFzZNaON9qo033ZNow3teYat0BXEc9IiW3zZIVTYC6a8bFg3+j4QaPAtgiXzm4KOvX1rIrMdGJ0CPqFNEw09PnzF95LL9IQJHQUoFUaXuNnkT45pGs4fr4S6V8CITpvPBOh1TIYCnR1PH7uGiU1unXTk4DfU9IcQBO4irM7souutSzNYoyn1q/8pqhpp4JNdXKypcyvkbWPH6yqrkqI8AyhZezl1NQ==
    admin-user: AgAGWvYUatqBO8/uIe6OjTLnACzYaESYxkmhYtwZokHaogd3xlvGFFMHiaoSNpgothWZ/5kaM+0ExPoRuOdTH/AmdxUvP6/A1jjgZyXTF9Uyz6gGgnvDde15CbhvpxJxDSnQ+eD2CW31QcYZC26YTVjuSuNnvxN5S9mp664nU7YhQpDQF854pi8foD8ROAFTp+DG/w4MPHPj6nlQW/lQ7rp4xd4FApMjEIrw3Npap/qPmC1ABwofpSi5fG59v5zL/fHFpcw7y/fSiBiedIswbsPyuxbLfE34uVmZBD1lqDwV/ulrRLJrqBzK50dYBjEqJV3ie94pg0+LW+dMlvMhNhJXNPe/K9ihub3r49VO1+JI/fLy6LjRRqGdFqaAXq3EUOuWCpx9tgHv46ZQjQv578pp6APlFapGPqs2PRGS51OVMipigRyoT3yGgriYTRZyUFEDcsQmTQqgLCt9b4kYXqKLtxx+xjaQkUBUYJUNOaweEE0uZBo2KbtB8bslqQ0hTN6KTlmXGmkLD00JuhjCILArLdyH1QpgtIC4tPfKMwyjR2pRCHuoOiQRLPVsSEaUy+BgSsoEQzc3TG93BwAgSqu9AvU8zqqGP/0s/NGcqxb6EB4Gob93yl5QRtWtwoRoSQ6qh+eOK9Z+yks4EDGiTtMtYWfGmW932xRk3WW3vNOoUYpTu6eMMPtpqz+g9WL0GLvj7/bg9w==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
