---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-db-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgBXuLUgzALOOVXXR4AoGsMpZCS97dJcx3OBOLBsa/ii81X23LQrWFeWekLJ/XpjtySKihtP7bRWl2JooXJLgn0aQgXL+apW6xSZRMUN3gbios4bSUPmlCu4M/fEt5f15Sy/C5J2CXionsIvho5rLKbGPtvEMpKNCTDlZs2ReMMi57XhdWaR1Ht/3CX2IyrwTcGFb908bFZgDsiowl4JgMRRXdEAIt6W0DBZDonACs7rgwCDO3h1DKb/rPnoETvEteK2VlRAz/+BBp/iw0cBPP5cQMGIQg7DEDUS7wF4WKBjs2n4j8lw/dHFFiJu37WPGE/HDhKQjOXJQL6mrvgLOu/h0RV/Z6N2KKh/AG6wrdYdoGUs6ftC+dVSpC3JtyKPjCYzXjZowjPMsQHYYKQXZXZGZfQezuC5rkGV3x4X+ki7Tf4Pm/Oavfn3qLw885lGW3WfRsAeM8vKo2qPZDfA3O/WOVl1l6XwNeOiIprse8j1GkLLY46y4ZYazir11Pe0LBcRDPCanRDA10DQsXGp1Lbs/o7IauN06+OgsXrUQiqVfOIFWFYSOvzC13/a+wdugE4kRsQjwxwh4zwYFSMuiZpbAWyoIOMuRtlIkLtiNnvf6ZJdsmw92Tm/u+x/NoAoi/okQQRxpeDyQH43ujWb8n0jOJoIyAQ05eGzeWoEB8eIjmAmUvREUkJrv4Mn97ppnBSyKBUmAWIht+wa42k1vnzXH8q9dtv09xrFT69phS48p3H5TX+c0FJVU2LJTpOmfMg=
    username: AgCqEYDgXGDOfhFFbStLNP33vp4b6nSudRLoQW5zVQkJGzkyV699wsgrOaAtI4Ypt27gPOOV4twz870tQqS09+fNOq7hLlpdWQfMZCzcs0PZ8cC7b1hQwkiNwsJVqtYsdezoqpCZxuP3WQ3B6feJjlw8JSr6FBrWg1Id8Wa4Kw50996i62pZKQHtTVvkOYeO0L9EL8srD1/toXdDOWBP6BPw9CblkG6ZiO5aWefeD3GKMxbn2HGWJKQtSGtUtZN0ub63WGA/8aCZiC0f/dYOPY0SHG4XXUKBshS5xF9Nyq05YQwDGLSukzA1xQCROKwsyz+AwPmKDJXU8qG/z0fYtOuBwCnxIIsdr26SyreiVPkmpPJ8NQKNRbos/JHfOFFeAi5rrPUy+4xOPs4v6W7SLQSseQCCwS2iOgbl9zQymANv/a178gEE5rQI4iBYIzxQWh6ii+3FjvwImd1BDswgEkYdO7mQWOU/uApKp99sC7xZUoCjlAh732VIIoyQX2P/n3a03E2rRL9DVWW8lnK9hUSbTtM6aP0UPQKVCORbvICjuB8jS8oPIKaWuB2QT3jsIigcySlZPHbQ3TC/BZ+Xgl8BLdv/Zg2aSNU5Ds3GOAVWJPa0LKSNLO3uWk/72M2RAAQG28/wZS1LB8OEFesfjx4TKx1uXARH4YsMob6UDZ24lDZ0el1ocm0jsH4nS0j59T2fheon
  template:
    metadata:
      name: auth-db-credentials
      namespace: infra
    type: kubernetes.io/basic-auth
