---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-db-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgAYzVh4Zp27cU1sJtgq6+zagBYVhCdvVVi67yF97VjNrQSaaaMs+kBs3tgCERNbnZvncATNQU/0MYbmF9ph/nSFqPd2V4QZMv4yLAeoTnbB0Z3fR+buHXxj9a374Ov3aae3o61psZgcB8/+L3vQarUkiaWDtMicaflUHo5AHhUDpJ2ZK4JXps8hKupDL/1TBzuDONy+H+N1storJB4uIgU80zGoULfisgfsidcUd5OvDJhNXSLde3zYv56mXM6hTlkfsG/8hEGB2+27GZrUiUwH/NGRpkJNyB/b8/meq3ItrXJgcvbThdRyIgxR9k6JAez5CQogUal+uOfcRC2Oa1REejIk0WLvY8BK45gyqy5Oh2XSCXjDK+1IUyPPT0YXZ4OrYnXbs5yNy6yLmW14rDB4yI2r7cL7GAyeMpMd+3Y3GBxk4WZaSL3dqhgp+VfLnqoNAPwU3SGKQ27YZs5vjiH+EPWsN/6RQTSZpjztHaJtEg8iOk+Yk1zdVbjHRC47Rmpq7rkgdzuywTiykpSoqZ5Mo44mqTGaK54Ql9I3QALvirRLXCFP2HbEtWHLelZ4kIrjomkZOm/NwixgN5WwWRtOD8yJepGE5ovA4plNPiry17fo4y3DL95QTOfgslBx58y/GOKR8VbBgi0nTAUBVQJN7ybIPTukFwPa39LtuoEPRN/57aekoIpOP6y3VoEwUQTYsRi5aKVumi5zOseLrh4lRHvsXbSEGMLlbZOKMqfshld0WXLpvQi2nrxHsBCfrFo=
    username: AgDO/1QEwhBKhk1Oc5ikgB5+iuacex1ccRMGpy3T1K3ueRLwx2bs1UoNwPiWsxG5Y+MbRq5zHiFqEW+bx4l8foYAiqFXmwlNsrCg+bqVyt6YmMj1PEfgmHUaPeMChiXkgaiMEcE1oAVNB9T78BiZj1CWgZFwPAVGYWiFYd32m55rYluReuwPofDrhpCKRC2lHftLk+/RbLLswH5CzTzmyY68eeIaeB6d83rehVbACxpD3FxC4jVKe/jKWAAbZwlTR22X+KYMk1aSXbZlTjuO4ZQu0+53aXY85AfHR/n7Sd40+FU/tTgx6I4gwrYhU4Hpi0c45L46aW18BmJX6v8Fbb40gQmEFPi9uyNyrpC9xoBdIktIMDS+a8XhunBYNSmJI9QYO2bBVyZnYuirAKpQjDr0N52h96f6zBNEOecjDLkmRUVd7Y8OmQwDevi3GIuGWZpOmEwy6c2v0dqt6pQguPvPCaHn0cIaCDKblgJMR3ASCgDsCynnFvR8huyNtME30XA9rwYnreCHWCVsF2NX2Zei5COQccZ/awZyCvXWU4ovhTEvMKozLQh1g+USIuxyZ3ijNDvhHg/c80g+YWQgOyIz5GiENVz2T32KyeAECpj7wnh/CXQNomkoeL66Dal97HLjG3pI9T6TfUhALSlkQVD9kT7jQwHJYEg2UbbDYtAzsNRFQyprGltlK/J4Xrs/FjPvi0SvCvEzCmXbumNw
  template:
    metadata:
      name: notifications-db-credentials
      namespace: infra
    type: kubernetes.io/basic-auth
