---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-backup-credentials
  namespace: infra
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCho/r25T82v13DcBsqL4XxVvFufdNDNdhceXRaGN+O/CpjrjtDZFQkHtuOGMsq3tF0QA7Os/3Gg4upCPW4Yl6mPytUoei9aDa9qlOrG7VmTpkZ2ycd+prDRugZwXpAvVR73OPnFprhlS4OAhp+XKgV8Lc6XGx1/yhNyDeHtx+8EgP/tEMjM8hExt9D246Z8lK1h9GFrzJTrRR5ycuDqlt3Uc/I9QB0B+grgPfld9WPcdkfR5X1vccOMaeD7jZqIgFIrx3PgxLyc7EJU6jzdgjSmxKwzIk80iRhLgrVoVfxO+CHwsPx/tCrrCLoJIjtXlvr9Mrz9yo9qlMUfpCfBU33OuJAGILzDvIDtRNo4YLIsTB7pwssXJ8Q07OFfPkJYvI6G6MqGMkmHDrG5l8UU9Is8qh9Wg/8qUQMHcnT/g5K52AdyR26D25Sm0L1dXfNfVL+uhy8ozn0cEGuhNMRAs5qU9UKwWI5e5nvKIHDT2UK5PgSic3RMvoE/6O1HLB5cWZzPpxN2U8dOGSXtrLZiRiuDl/gFBz3r1n7EA/Mfou/7M/bs1xEk9FNG4/a4lDDu4ON+NZKas0LqZP6r/xs4r+uL04lOtxdFcyyodhfimJ4jE2U6XAPKQ9RHx/M/TGHmWzqP1Px2geKD/lzzwsZ4WgbKvMLnKSHLr4NeyJ+QsTO0WknTZTAF9AlH/Y09qqvVnd4KdMnrk99A+8AuOif+mfmpMAD78NhqJP2Q3hBUd7CDg==
    ACCESS_SECRET_KEY: AgDCBLUMoQ4KTaPV2Rge/2ubAtdztgrP2UGe/rZf+L8/EHok+cA0kQf6ElN/Yc7CcgTZ6sRJy7na5KJijAGxP26sgsyorij4aKv1UBB/xFMj0jqrBxbqu4QBvFapAQaqLfYWQXBeEa/J/0OTgXxNh/QZxdv0KmwPQEi/iQTZYKiU9da7xRCJlNZt+LRY7G+PIOeRazfL+3DXr3V1vBXeHb5woVZnOcgCqG7R9yVU+EdreEExGPblB9v0e6lMhIs+vqvxQO/If4flOtTHxwv3c1f7WRyvgQJNfJYi+MIRdSBJm+YBArA61iPq9HGl/VpxTqu438ZaFswjhgyQwiuDkdVCK2XkRPNMkuVvyIN5BkbbOfnTOT59f667X3qKkuuqzggndx30Vw4OUrpfFSO4DP04dOBR0ICsoO4qQO5jm2jlr/biDrRGfZDx2ZaRJWZ3mFeu2TEVLkgwuKpFYeKAB5z0+tozv2wWxrI2uDmzNTnm1SxxSFV12TQBZioXtKgaxLcQhXXHM+BZn/U86wFVRlIzBygoHx0RdHlCXIWk2zYgrEZUw1LmZIFwQsNI6e2ZvdswKI6tzqVNTS6r+X+JFhWu5zYaIxJdj1l9onYA9kzBUiJkG8fKlnLtnXJ1f4H169b/s80W2BBtPnaCqJapWlnMBnI+LJ2txYeQbJBK9mJMvljfixdAZssXZxVgqSMWfZa9J7G3w12b2OyfJ7UVItlTOPeOPNGxUVD+yRhanRgiYc+m9t7JImrsST3S/9v3I4kxvxbwsYAYjeOLzJlE41/B
  template:
    metadata:
      name: r2-backup-credentials
      namespace: infra
    type: Opaque
