{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "outegro-service.fullname" . }}
  labels:
    {{- include "outegro-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "outegro-service.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.podMonitor.path }}
      interval: {{ .Values.podMonitor.interval }}
{{- end -}}
