---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-password
  namespace: infra
spec:
  encryptedData:
    password: AgDHLVloIG8zsdZLUcVOIEqnOf36zvz9yoZh/C1nTDdBF0hkXdvidENbLeK+BbMzqVqnQwgwbyjsZNC1VOxnekPwCxEU/LSNDflzmZj9+G1zxkofHfYAVbMrKSt7Q5VQwinSZ7JhLYhUn9n1+KeXkjZCpcwcx9E93rToZunlrUw1OeMnlojOK7Vh9zrbxKV/85CQRUKyU732bMWWYX3xREJjwGSPz5dFGUXnHHm88X+7Wmcx/oDHq+9TKJXh91Gd7WIjXrffd5Z5cE9XwfqQOlVi6eaW4+DMa0VVlFo3/D7XZIef60wGJvutpcUXUWjMfKDJ7vnkUsXxwW8YINDgMl72L9tXrbd5YWkUG2HRP7OIAFcS/6brhY9Kt4dj6+jr0AKuSOl0Qt/Yxa80RiTz3AVKNzqej+3iwRWxrqPD6BBPiB77wYg7XDSVbDjpHRVroryW/CLKRj/AH3OhO+bRFC1Om2t5tNdELKkQ7FgJyStk0apC39BlSaV4KlaYXPNuOMbzoRrlN5u0Cdv3t/3WBLH8hgd8ACibjgDKrwJztrvKYmaDohw2iraASXRBh04O9pO/SAeZDQ+YywYcqV5gO+ouT2Bjk/i2KnBSAel/gGqnIF3Zy/60DZWoIL3Qhjjn43RRq+OR7mpzdkb2UO2RR2ZX8R7sWj441BMZBhqT8KYrvM9ip4+/m7yOHcjtU42ytHfH4PhGrocPHbkcySmsrvmG/yEen0XC0MMUaITCfpRzpg==
    username: AgBg0F2bQ3ut/qfsCBKXJOLx9JQ7nlr7VRBltsmVB3ecip4/nD59mdpHaAGiSOsSgaAxTPL/DRF9bAZO/GoRarVgtfDUrpVHvptQfCAq6YxiTeISVCBVAyC30aBdbOJ8mYZAh+eCDr5SWI08/YbPne8CvXBN4j2oNk6GccEuzUC/Mugjf82+YSx2ZrHJHhVaKUgIq0/B7aWB/XPvb+BPFjtxNFc5zmK4Dihahry+xx0dk3rB+Cj1B1GztGkggalv9SCRZaTO45OtCb3FJng3ZOgx/sVAHRTkBSBr+hfd2zY1TlHWKUwWsOyh3DZGG9t9hOfnlnlRXdEBB5pZIMdDkxtkgPTCRflJr1cyTTTQZ28snlc+QrfTB+V0ye8dQjhpOJxutdbm64MY8YRiL6T73ohWAei1aKB4IaB9v/3ysdv/stTq/Tktefh2C0t28mPyWr+sYeev5HyAfabLIAYkFzf8okrY1TvwsbaOU/WUSq0+wglIXa/uJsRb0gypLtsC2/BwxSx2WZglYBUvYS+VDWfRrn3DmfojHmOzQgA9OmkDR+3vaRqKfqNHwNgY/bwKcPYJeHWuedg7RBDXWQ0Qs8RTERMLtf8b49vZlWO5bbAZAK2MtyAwk1v65/09EUdCWGe5GNpGsuz6WUTeQM64jpEe0DJz684FsWKAbTicWRvJx2+YLigljeJdNHelbpECp1/u0x4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: app-password
      namespace: infra
    type: kubernetes.io/basic-auth
