---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edu-db
  namespace: infra
spec:
  encryptedData:
    password: AgBFyGyuDBbUZI5+MuazDefT57hyYB0/y7FUM0sAdMqafInJPJHQi5ZcRdbgBezZZ0DBu548neKiJUCyqgtit3iqQM61BbxhSD1gLHoa8LYgvDtJbwOQncaSFSjgw5M7D5HYnZuo6gi9v3IPLAOgmjCzaRmYCp3/MktbtvF3ekWN4sjpYTn6EnXAJPNikkq6WPcJKEJLIHBeILdsEwbdA5ykyQxc9eJw4WnypiqNCa6wSawkU5HlSCnDkCpLrAqC8u9XFG5YI2dwNR0BcVuPjXXAgkVOpmaaNk1U5ukeCzQqsXMhEhlMaGPhTeRgwDWSPnaK/aATFZjgjClu/aIF1wr0j0MaWH7ADA7MXnVK3ZytN/gyf9FCrvEqXOWZwxRHGokmTl4JIXz7lPe1yXKfRrIG+FFjokbhIFSeCxVonD129D1qdYlUUwHTK5IlQmnpJ3BKnUAIgxlCgGl1GTSmWmzazs16EkPf9JmdcYnMNpMEwWUt3u++GDTbg06yeAompF0Ka1ujmI6XsWyq6vhM7ECiTNqxVXQyWfOtBD1QXR6NiZeuW5nkJLAU7EVrG9lF0rybDhMG5/5xoM6YsngheCDuhvJt36qDgCEitff7duBmKire+29Bb8/5stMZkHz+Gris62vap/+ok83ItKg3/eNasY8zDlGfLIRzaYaPrL1b67UVkKHGpwE6O9Rcx7UvBb1wjO9PNnTtMwwgetZ0Umcb+/hkYgzTYXS639mc7vJZLvOp/gQe50YtvkUgGA4EsYs=
    username: AgCd1J7aahLNsMgzO6rg1ExZrGCbgAUNWbFe8NwYLZPvze2RUGW6+Ahj0W8ZXElAaGQawxX1siFqUn+xD9ets4pBd3QzKczt1sXNyRwRO3CAsXWpIBAMfFY+HJYMhYHelmvChcQoUihKC91i26Op2l7cR3lqcaQ5ZcaGhHKHYKroRubyPkY5uIjnhIMHDAyYtaaBaZacmFmNKdnLoVxcvBEWTev2teJPm1i8voiYDfK08+5GBfbhGuzE6Ca8Re513udWy+8bDIAI8/ddH72PaM9JRGlqvNtzpt0tTCCDIuZO2XtH6EPV5gOWRITfMCNDvI81kk3dhqAgPRQb/qgFdbrxupyVBXgcU8/dtv3q867P0VgQUSmpGkzyd0UneR9Ca8IoLWjBxT3/OOXrq3fzKg/vOQpx/aj4L7O0IMWF19MzhHl7D0fd3NqDHgVoixgOBiXdtxa0IocEDo2Pb4hxuAc3WJ/7SQH1EgFHIvQQfeeTS7KvlXg3ykUhU1TVIwabhM3zGxtDBEU1jx3YH39rj19Lqa4KJEfsH2KZ4H7GUjaE9CPpk616RcMwZNsi9OJyHzXFZO+mfip/K2qqyjUXnwISJyneBFrQx5GUcm2x/MI0Gxdkdi2FRlErBG0829P3gVFDkUUr9c2f4oropuofduUYN13F4U3G9NTZqyghKAP2j3H96eaXTJlcU4zb9/oSdUI4Qyk=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: edu-db
      namespace: infra
    type: kubernetes.io/basic-auth
