---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-api-ai
  namespace: platform
spec:
  encryptedData:
    MINIMAX_API_KEY: AgBUK5cEXc8qCp2K8Z0qHbLSt0Ez1B1XJFGLDBd4i0tLkuS01wxUe3WiklsXNt+9p2WwD5a582AK+3TkARXA0y2KZx3BaLsngFFnTMj8Jaq7083YS7i3M2HOQvxuKKlPZb7XhR8EqQOGtMJ3VuGxRuIahxMdKLAbIZzitZd+cL+l6eXvtjljpgn5qwETCwVMe4SmQq7cIIi3rGoOuoL7JBmQnLEB3BYSSB4Jl8F3wQm5rySW42p9N41fICFfl1ohdvFC3z6paxOK8Fy5Qvqcn466n43+iFEKYE9AFb7NoCLPsW84h7P1KCYjrg5h5dHVZh/yUOs977s6v2pb2FSlE914chxYDpaB7xpUUoIUqLDv34KaICjJyVmeanTQPjsabvwK6UnvsutnrMXgTrHKXJgZNEKISfdK7KHWApp7kPtPDd7xrf6kTiwGjfc26ewH+XidbaELLJobNkaObPuUuXo1wVzAb020afo1raSfG8wsAPn05tL7v/3O+YMB7/jPlUlpyloast4D7MyYfxZir+qreHRZ9DhnQ7SnAxk6Rk0YpJ1g3WyHrSgC1P7OoiZPxTd5dOgz32w0ZOI9hqQteoHrlfKK1S5gS5/Yn6TRhjbWFzB6cFxE8uQgT8tORFi2PBZSi/N62RcxR+NI8vmDGfFOdYOrz4dl6F3XgjifRGETyIYX2mMuLadmkOrNQ9xiSCwj0VzktgK9nbYp82VzxBEJ04k/hWdnGTjaprBcriE1nnNEqQBoJS4EYNdE6Xc7Cs/tj5ASvQ2xCuAWn68WwvLSQp7b0b1TWLMi9143DC9uWJWXc1ytLSA1qz4qd6Q9eV2KQzXyZg142KtL4g9FIVIzvrtjvc/VSSd1FFGbTQ==
  template:
    metadata:
      name: example-api-ai
      namespace: platform
