---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBcMVQDQDRWQJj2+axm8n8Yq1jJMjzI9CJk7IwGaljtYMS698cKKEbN3rzmSqfBy5UmCVwaMQ/JbDELmDbCyd9tv0YChf+uMXWUZopoZuBn8wJBnV8zCz2fbQs1Fs2hVzNPLN+xxh3HzSNnOxq782ii28U02LuVaca8NBTXuZ0knBlTjyytBfHclj4a2hSRpUYepbzzb+iz87l+J5yNrWyxXFZVdi2ivHLwYwXPjr2sVpBKnfBCdt4cbqldMD9+MooqQ9uHOX30hMxviyxiUlRetVXjoceGkJxgfUL2aQfyZSzHtrcUpXgrr9QOMxPgJ5n06/pS96rhGaezo/aw2TGcCXmQ9ULGsxP6vAry6KSRMCm6slYIp2n3Jlpry7lnAslWLqIS4UEjPsNq6vg4PSRCn+ZDQJYyBuGu5bd+O68fKUCI0F2uZlu3C1qnxtAOW2Se8EBxXg4jUZaIsc1h2zoUlz2lf/bJZQnb/hKMY59nlp3qNgGTVXtGOB2O5ebMe6PVJ+p2w+Scyx/Q8hHBXsLoNJNfP+fVD9RXLd8L3tkRqV48Fn8XwxDSG4A20vd3QmBRh5aJ0fkBP+VVY7hzkmT6IhHg4pv/wDq6S/78uTs+lvlqCkTfSAHXWcelBhSJhuKwD2xpA5nI1eXWOcnfDbMD/C9YcMBat0TfAA2uXQbDNw1kNhC99SMOKi++m8CIdIB9C15/Z2KqjwsEFWy8ShfmfiTUQax4oKFcQ653M9jO9g==
    admin-user: AgDDMsAeN7dt3VfrmyXs0II0pGC2GOiN6+8lthsEdT1Nx1OwwtzdbPd4zkRlugto8htH278bzmwaF7XBOLMzFcmyUD3jFQntrZU30JAUBp6Lcxv52qCF3MRMXJkAMz7HKOJcKXt2KpGeJYRowhfmRIOxBpAgAgT1NfZ1Mpmq0EDi8MipHg1Iw+D2u4yaLTWX4aED92NzYoJfCORxUOZFdV02BPsP33dX+0XRIfG4gs64wLtjqxmqweGiRvRXu0RRf7q7+OEWepca+toNNvmOYhaoO+Zd5ajZQrPErQiXYjH3Qe2APZ2PP7yaqQp/NNxc6ZY/KLww5CRNqntgnxGlaahv2H/itr5ksVjN8aDhHogBmKx3ttccZjVKU/bxr7CfaRUwwQzzg4bnKb+qyqX9uypDRTkmJZkZ+H3FwBDQzaghLWznMC98etEn3zJ/4blc/kr3KIo+tc4BpoMSc5jyBkJzh9CvWubWUXjpM2s4s4C+w2G1Gm5fsIGUwLc69w2be7iSGFLorR0otsD4JAlRIYfYU9kvgZ3FNqTaO4JbSfY/dfvIvbhTYw2Utn+GRAF7XVBLmPfoM24I81E8B312wo98ZS5Rx0srj4kXsEjydydFVUqYJV9TFSJKoFLEkOanM5JqLaYXfMs+uVMo2w7ZC5qsv+ju33nNpPwRnupdKR/OqrPhBv6yAWFHDo/LBDy7yDYVeZo6Tg==
  template:
    metadata:
      name: grafana-credentials
      namespace: observability
    type: Opaque
