---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-db
  namespace: infra
spec:
  encryptedData:
    password: AgCBXEK36/NiX4JJzWkchB8RrS74gvCAkTBdgFh0C1uzOi0xYEJCIlmJHNyplkQ6BA/8kuswzJhQFdUPOwa/VDjo24EnlUxnzWlyz6Xol3Y2oBWjcNngkHEY0TTc36OGp05B1RbceXIK9wa9EWbD98gaPm1AGImr7ivM9xcYV7U/XMzczxPJAIOBp6QmjqY/gRYPoYbAyu/AcU0GKXkN8/SoUA6PacxFfWP1mVeaH0AWDVdaf9u/8ts+QV1o0KRpsrs8TbOY7IV/2zO257+ayzdNK+NZxgJ7ryVY5VeBh08xOaIUhf8oOxb+x0uma7p2Xs92U46NJZbykfUZLFxzZjDYa5PykTR1ma1qzqEppmwRD3cLrctLIQP4Osju+adaOyEidXedHkZqtxoMAMKNZNznMMJNhCEOAw9JXzhMgoKgwnLytsBGtkWhcoxU3ZUQgCYGqxk+CnKFKozpvB5drBWQ4VBW6E9wY9C+VJCcNUFLFFODYJazM9SYNjV7iCDxN/DX5+R0AcIDTXSTZkrutI83sCpG3WWiXAmC98nQJnXPBehFOfbs+5V8cHGYHNDZ7fGrfLgncMEts04OuBcuhqbfZH3tAY3qP7stof0BAiUhmy1ad9StGqusQ6YqjqjMGw8c0AQJl0LV7s6StHBuO8moes/y/MbXI3wJKxSBZJoyKG9Jh45FIqStUwiL9LT5I43G8izB3oOSaXFv/HZDQlyafQaAq7Td8BowwD9r1EDNeQ==
    username: AgBjj2C9kBXhiqRdL6LPmM/GRWwQVPP0xTb7OG7PV4CL+rRKmI8wHjVscfLurRQHjf6p1+Oq/dKSMwBDcABhmT52vv8Ejmjhtb9jfn2v3+eQxEEkggN1BoDD3+TsrjyxWbJeYWPKH9plXIiJMXbd4zYc+775bdOcpDnDxxqdkbecikL0viKe+9vFEoj9M4qs3B4pAi1Z4BZQuOladkTW0f/KRrNYGcu1HHZIm5hV8Kg7kgd3bzPbTScyjWuj+A6z04N3dtiDKgpC8HJimWrtuAKt1KzmoraivwFgLXBOaKy9fe9pL0mx8V04XTEmzGUpnd8TsOe9JISUlDKBUmrDOJ14PVV6l6GbGHBvT6i86DbZ6Avtk6TXVbfWBoVLn6EOHw4qlfccE/AolJprg13MuHbSInzIuiwTViTbEUSGJbhSA1+FiU9s5UfRI7/ua3foBkQAhjTdo+eIHJnCQE7U0NKGJ1k/ywtuxDYfE/CcHeXN7N9erd3Zs3A8kA0fcrNimzFvyaifHgSAf9Ygkut6026UOc5fFOkXSTfl/0uyUfgEkS+6EL90i7G/A9KYclVUoukQuv8XNdROebtxeg3jBXMprDG7Rstrxrj8CwXfnK+qfLNEDwaLJ4GUymyu99sBuRhT7VKR7KqouSpFqCe9FLejy3LF24EwbfbTmKIHl8en4KqBED2sT8LjJKe3UEyANWGABOdtvJ30PBNJWG42
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: notifications-db
      namespace: infra
    type: kubernetes.io/basic-auth
