---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-credentials
  namespace: infra
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCbCVd4z1TQH0BFWTKJvlBjtUO7BBIzcdWjP+/DprOqtiFddYb3IZHNQBf27y5DrlCwKZKjcKouCUA1pFMl9pw4uyRP/0f3bpw6wyRI7o271NI/r18T67L++e5EPHHkFh1Z30k3dt3MDBxxSerB/VlKuGA+13pNkcDSWftXgt+LeZO66BaaH6CxaFxgdUXFZnZ7+BpNmnevmb8InQRzgp2YxIT8lI1s6nlwlOsfp5nPlJvUO0IEl0zJafzkAHtodRjTmvcwVdeKQvLcalQKGGXTo522KYm0pTuxXJuu2ml8FpU14geBy2CEaadSL5bURX1ueHbAR/wUvGrW50vOnsDld/An64aIHR5C7nZGg8zCpHGCROOJ6Zay8VkUHh3ysX0794LnPvF74H+RhjWjtKKXddINmk2TGkfvat/YJuSVn6Fk3/a1oa0CLP+pLGFThCZPcBGLesTaSeL+LfNA3wbXTV2HYg1dvWZnc5vC4x3h2REQU1Cya5c4IjMmh/3SXsjpVw2TUGnMqTVgCCA7RsXzSscCj31xdmKIMA00t12ndQa2w1l7ywzdd72St6upLL5cTVsblQwRUNBImQUfejn+Lb0Y5CG3R1/079K9NOT+tw+T+ci73AO/D363jbFJddl+isO2tMsVqf2NYczF24wC4uIJ5t3ziA3GgU12CrpjhivvHzMiy0QSYgz5HsfFXqKvCWR9qHerzLc1bMTCsQr//ZdPh76KQyIVjLWhLWLCWw==
    SECRET_ACCESS_KEY: AgCCl3bB3Bi3jUEgZaWXnnPH9uAr0C7HHFs+TjHlqn5gAB5wiiXb/re0G+t3emaxVUIk4mqEcaJ8E0NkVFRBqkLsByUuuCrn5PSC5VT5bzSMagj88Zyq4QGUCFLZyb2F7/GruaoibsEy5Rbc9Jxgg4XbpadQHLOCWIhsSGW2Bzp48+8m6wjG64AXj73QpJRDSsgoo1a9dKUrer5Cp7WnEv0JbfpO4Fm8VfY4n31yRH0oJuoW4OHjZrVDtZDcYrQnmjgSUYRtWvn06pA9b+tOlb1U7wtLQsqQWPEbu13OfqLTl4ZKc04H81PrastYhqkhngBcFXwlUpvtGeRgfE7TvKNcIDK5W2tpEDxFOjikFVeNPMeUz8aKH2e7I1zftYrDj0ErpeZDuT9gmvQfUMPtXcGhssqBn2h41BKsjigklw5CUs2GR1XtzcebG6TB67wEgUi+/SJ9cMp9qGC9SFUQCD96bpYxBimc2wMahKL6NfqbTXAUxEjiwA5RkFJbj43QXWELE1HvYTRV41vw753y3d4cCa9QbuERABAi5BAlPBdEonO5fOb1MLsIXOwh6FAm6w4dUiQxf3g0i80awGRCdMMmgobrRFOXsEUNjgcDRqTrLJcccPnZzB4kdXZ9vJfvVJWjnrDqjQDAhHrtq1La2Fy1qLAMandBaaFFDMvwf39+LnfiTl7DydH+ApAjHwBpvZIS5PRCzMiHe04kLLIy2gGq4j52eyWC4YAv2brbJacyylwBckoEroJ41HLFjOM7/JG8lkkyrWxnuAx3TcrhTLyo
  template:
    metadata:
      name: r2-credentials
      namespace: infra
    type: Opaque
