---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: infra
spec:
  encryptedData:
    redis-password: AgAt+u9uUtYdqHeh8XZ88Irzz5gtZPt5gPMYO/V1BaDUIMQyZcI+OoF3D0mtcZykSizwBs0IvW3QPJhp8Pun0KgIwXl66IjSvcOPsUtPcI5Lwk6zV2bX82ylMlznzDQuULwejNfyUaIGKtsud7HW4Um+t8KH+P90OKt3piSaK0rE7WOU0QmYgWuNbV+BL8+BkWhazexl2KRdKmEy0qfsOtXmBIx56xe4yEsGsl4UYQ4fcHiDB0OShE89CPtyUIL7eCsiNoiLT8gXpgG4CAx1/qaO+BAtXyNHCrZLJ22I3xXhzJMbAcv2QCQaSIb/wz8hxnbm9OchvxqOYWJbv2EfHfhiJFS26MWkd1Iky0Byo9CLyf4/9cV/lPBCC2W/n0zvm+goHtxkSF63l5taRqFjRQ4UQFEQIvnO3ywmzAT6dycvZgvdpaYL6DTork2Dv6W1uaQYp6h87kaIX6LSoXqZjiNlkNjeHUv98OEjb/piTkBsm+LlD51ETnjX8TAFoc4nyBQz2ZsCJm/aOmQE/inRa/K5+bS5yiDcHm50W/6bAyaCKNaAon4pQkFJspBv93Qrei8H7hoLNW+Y5LJRf28V/soTA60isF+1UKgZMv2Ff3ZvxDzHz/v7aTkSXSCzZw+cDbs3hbAsoRqtudfSgrQrtZlggy3iPR0F6TdI+RS5gYS1vkjNQ8mF+3kRyPaI9zWbs+rh7yB/TjKAnKV246Hm5GajOI/INBnCPsctkzqzsMicqQ==
  template:
    metadata:
      name: redis-credentials
      namespace: infra
    type: Opaque
