---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: infra
spec:
  encryptedData:
    api-token: AgBB+DBSrW/uUtWj4mi/esVAk1Qz3fP7B6a4zNAN9ed+BEziTDyIDHjLsCvgcC5AqJQIP0pg3f4HTK1+h6q3UNALP1kcSqJuwLPET68VDkq8egqB2iqvsPcID1ix//693rtOQV3KcSJYDP6lYm2bc+EbDltyziDHeZiUOoxqcL5zpp7gxAKE0laLkAspXVxM/lX5Uzr8I5Z7OpVBAHQYh87MI9bpQERnCjSsFcXAglakb8+khXJ77EgBphPmPYQYvNebgT4zV9mXH+v0LBlptR1bJHMUWsWihSVpJ7sIF7zLKy+Gwuvw8/Y1yTt5HtmzozYa9ES6DTMnmaxsID6dNR2EnTYtFKaCsHo0Ad+lUEuaDSgE3pmqGy92L8XSWVVGT4bCxFhyHMsV33Zc9sGSdpL/0hhz1lE9ubv7Kc0FGhP5mI6F9bQmQRzgZx0BO78+MX200Qr+PWbaIk/u30a+a5VAVusoRv24NDZKOSH+H6H6Ers1WJ/HaCcjVNMfzrmOJqXuzG6XkZMuJdzzFsLSfUKjpVjPMHVsqbk3tQdBEHaMHcMvdFc0+Z6fJ0cgGjJgAXLLcTv/25lIi9J79Kn//QI1i7gcNA6yUxkWHjqYxVYGMY5kSBia4kbURwOPb+NiJ2R6ktPBRCovCmIGRgJTsheSEQBhSgkQjuvz+WDZc+/Pw3QbEanQlCVpKCQgVU+E3aJRMMxoLAhD0CC2uONYvQsW0sXfy5tMetGuo6HPdsf1qoJwm0jvPeO/ON50ThAwNuKzh0wHZw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: infra
    type: Opaque
