apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-web
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/outegro/gitops.git
      targetRevision: HEAD
      path: charts/outegro-service
      helm:
        releaseName: auth-web
        valueFiles:
          - $values/values/auth-web.yaml
    - repoURL: https://github.com/outegro/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
