apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghcr-pull
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/outegro/gitops.git
    targetRevision: HEAD
    path: infra/ghcr-pull
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
