---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgC4sKT2A2N2EBzik9PQIjNkq7FIrFHwubTG20a++yAulpIUT93PKEql4hFv2Mpt36YCnsXP5sxH8k9LgPsSyc4ztCcBkdJZ5r0wD5WX6JE93TAJQX3k8H1jdWwPrlRps66SgQGKC/coIiB8STI2G8+dubGr5UBGztvlxi9PeHlCK4J3xbf8Zhml/d1yj056PUd3XaVqInIZO++fgjCH9NfsamImB5afiyZuTPvW1SwIlTEMCQWdBdFIVkPhwtctNPsKNpHkAbuaiLRaP7BiefwtoPXyYQc+GPFOEHnJ7YTOBPITFT45EuVBjeR+DAi79cmwMnQG2n8q2DiErL3UKWWMLeGkM4RoDR3QTkHNwNZfKIyCa1YLv9U0V04gJ3zuwTD8kYwVu936QK3sJ9EzTrJJOwCKbnnms0e9Fhq64k/WlAzd5XKj3+9b15J2bUpxYDSX5ONQY4+FzSHatw+AUkBZTRZAMpJMOSGQ2/CpSMI0wASFzi5FCWTwlNPWyPMDfz22KJHmv1ntyHCPqzZGpZEBHqeb9fy4uB3npHjrpICb4K4OMPeehkwKHf/XnNmFG9F8rsogXf4TWZ9itkqzZjhEDtdp2/ohLRJnlNTPcIAe2rcmXtNBr4ES7X1Ydk6+WuMUhb1ij6QHuUkIiTeRsjQj+dKnpOwEDZsKjluAkcii6j6ccrZRaf9hFZ9vq603+qVjq8+eP89mjP4g6ayl0cYTwhZp3V8FQOzUJ6XWlf41/AfmfNcBehySUUOk/hsDaT0=
    username: AgAddKaRd0LOkDy6dtKNxyGe/KYS8c9Z/wfFiI/9cNzCg14TqDCpPTeN2tnwfE9fqC4IynMLfkiZCSVTqpgfq8jzJ/yDobE2F17Ay8XYhvrlZL7rgc97k2aGfXUsRY/4Xa1u9NAKcSqnWRuCzdpqoV2VqFXSroYRjapESjPXFt1w2ItLlLnEaPAufrIcyR+AlHfE4kie0dBeCTYHfT3xvSVU6lEz7QyJjDg4MfmjytNGp0T1+5tpS/eNPNE7GPVeOgf6nMoNtLHGjpscqvg0km6KhEt8+p3/hQYuV5HEjgQ/gfYvgtLWWRma2IrtOIPh5Ysu4GL6VBowohgP+a31lxc9LXE4im2J1rbCkAybHxP8AtKbVzjAEh+KN/qpNRyEpxwq5qY7kB5swBH223X/T9HcxVlrlirBeAMt9Gz1gdOcHf8+G+xs1MGyDsu6FFBrQNeEGAYOoXwj1UCH5ycv0wYuk+gB44Q3Os12fgRfSv+m3RZ9vaJYLZZE75THqdUW+sqwYEr61IEaOfVRA1kywF+41SwhIAf4SQY+b8oewC8XOf0IfO5Kvk0cFCuePF4Vmz9x12efTXu0rXExqjgPrh2rPkwRiVcEdpN137Pjf9jjkkX2c22xneeYMnnyNvOe9Av1/gP0nxGS7poWGvx8wIFeexTAmZet9JA7vZrIR0dbeFtHodCaTuFzFxMxAp7wNoysGtn6Oylf
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: infra
    type: Opaque
