---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: infra
spec:
  encryptedData:
    password: AgCgYnjNoaYRqTMXdsPDzblEPX9VnvfuKtwzKNN5EZgHsmBkuqeQ6iBdEg92zETighcTLDwwh9OhbCDdo8JllVjlrJFss1JINZ0inTvb5Z/lhsLXMxiNbl0olp70AfjRg7yULAKzy+uZBgOF3quXBHc60hmx2xfhl0cpRyEYdBW2B+tpdZelgztvx1VnGkJRpfTUIYkCJYedpGOaPX3LN02mvxvfx3pHOMT+NxermLWPBwuIHEJJqa/I9capgb95ai0jJkco3I2jYNDJjonHetnR69s3q1WxfQnVpz4JghyOpDcFwoxFiTTh7Sj8srvstoJG6TKEelK4GVUGFBWJu38PoL66J/iceu21IOOZnopTP5PJBEWRXT8oxHtNB2tYJH8Qaj8yKJQg6Fj8Zdm8QBkHxnU8eP1CdCgS1zGilV4l+b0sl6JvSaWxtWJg0SLoL4rS0d4FYhJDIqph5HcQt7MEggzJ+ucT7RCltHp+XCU+BoK6up2B6c5fBnoj/XedGpVdRtIq6X8lAT+e7fPZMv+/2ewvbdD+ra/PMuhgjz3Nnvs8B5UzFsQyTDGplwKUyTOMX3k+Ahy2cCvVtmtO54tQgypMaJty2PddwSqHektbzR9IZFfB23qKeQkdsyV3O0jcyhw/FQ3UgsjQJ2hg/IgsAnf9OFYFALGTzKsT7dSBs7h6FF7XOHwNfLo+LKBh6UWKKm5YgTOQb1oz7Mvyrui28rWwawicVWelM9QmSP1EC600NEFH7FSuOWJvnB1Bw40=
  template:
    metadata:
      name: redis-credentials
      namespace: infra
    type: Opaque
